### ISSUE TITLE
Trebnik: may need finer file split

### ISSUE THREAD

**Issue by pgmmpk** [slavonic/cu-books#17]
Looks like file chapters in Trebnik span several logical chapters. Should not this be split further?

**Comment by typiconman** [comment]
I think the idea here was to keep the different components of one rite together. For example, all of the parts of the Baptism are grouped in one chapter, even though they form 6 chapters in the Trebnik.

But we can separate them to have one chapter per file. I have no strong feelings on this.

**Comment by pgmmpk** [comment]
Done
