### ISSUE TITLE
Texts lacking structure

### ISSUE THREAD

**Issue by ENDrain** [slavonic/cu-books#33]
For a format chosen as the barebone storage for CU texts, current XSLT markdown is lacking structure - severely if I may say so. Transformed xmls require a lot of manual work in preparation for digital publishing. I for one have two general concerns.

1. There's not complex enough chapter breaking. The New Testament is an example. The NT consists of several books, and each book consists of several chapters. Currently, a book is a chapter. How convenient is that? Not very. To prepare the available Evangelie xmls to digital publishing I have to create the proper table of contents by hand.
2. There's not enough structure inside the documents. There's a reason why heading elements exist in HTML. Some digital publishing systems construct tables of contents automatically based on the header structure of the document. This could - and should be used to our advantage.
Also, in The New Testament prints, each new verse usually starts with new line - there's a reason why `<br>` element exists in HTML, too!
3. Some digital publishing formats, namely ePUB, don't automaticaly begin a new chapter with a new page. Page breaks exist in ePUB in the way of the book consisting of multiple *.xhtml files, each containing a proper chapter. So, ideally, in my opinion, there should also be a way of indicating the chapter breaks explicitly.

Please respond if you think these concerns worth attention.

**Comment by typiconman** [comment]
Yes, you are right. The XML / XSLT was designed to as a way to store the minimal markup of the obsolete HIP standard (cinnabar, w i d e, and a few other things), not as a full markup format. 
We've been working on transitioning from XML to Markdown, which is both easier to use and can easily be expanded with more markup elements. Take a look at the repositories https://github.com/slavonic/cumd, https://github.com/slavonic/cu-md-sandbox

**Comment by ENDrain** [comment]
Oh. I remember finding those repositories but completely forgotten all about them.  Thanks.
If I may ask, if it's okay to discuss this here - what happened, why did everything stop it seems so abruptly?

**Comment by typiconman** [comment]
People have jobs, families, etc., and coding hobbies generally are not a big priority.

**Comment by ENDrain** [comment]
"Life happened". At least everyone's alright.

**Comment by typiconman** [comment]
Pull requests are always welcome. What format do you want to improve? I think we should iron out any remaining issues in the cu markdown format and then convert all of the books to markdown.

**Comment by ENDrain** [comment]
I've added headers and brs to the transformation template, that's it so far. But now one needs to process whole corpus adding these things...

I've also done NT in full adding chapter breaks, headers, verse line breaks, and <red>ding verse numbers. Had to come up with some tricky regexes to match verse numbers. But in the end I think what you said.
