### ISSUE TITLE
Pagebreak anchors render incorrectly

### ISSUE THREAD

**Issue by ENDrain** [slavonic/cu-books#36]
This is how a pagebreak anchor appears in the source *.xml file:

```
<anchor type="folio" number="1v" label="а҃ ѡ҆б."/>
```

This is how the same anchor appears in the transformed target file (indentation added for readability):

```
<small class="pb">
    <a title="folio 1v" href="http://www.ponomar.net/cgi-bin/bookpage.cgi?id=&amp;page=1v">
        1v
    </a>
</small>
```

Please note how the actual content of the rendered element does not correspond to the value of `label` attribute of the initial markup.

As we can see in [Ponomar Library](https://www.ponomar.net/cgi-bin/bookreader2.cgi?uuid=7f39978b-bbc7-11e1-aa4b-ac670dfa6e4b), the pagebreak anchor element content is indeed supposed to match the `label` attribute value (and should be enclosed in brackets, even). To sum up, the pagebreak anchor taken as example is expected to transform as follows:

```
<small class="pb">
    <a title="folio 1v" href="http://www.ponomar.net/cgi-bin/bookpage.cgi?id=&amp;page=1v">
        (л. а҃ ѡ҆б.)
    </a>
</small>
```

**Comment by typiconman** [comment]
Fixed. Thank you.
